# Generated by Django 4.2.7 on 2023-12-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
